### ISSUE TITLE
Validation does not work on findOneAndUpdate

### ISSUE THREAD

**Issue by kurdin** [scottwrobinson/camo#60] opened 2016-03-03 18:56 UTC
I have model schema with 10 props and one of them is `active: { type: Boolean, default: true},` when I do
`Model.findOneAndUpdate(query, {active: "none"}).then(result => result);` I get object in result with `active: "none"` . Even if I added any field to update data like  `{active: "none", not_existed_prop: true}` I can see in database updated object has `not_existed_prop: true` after update. 
I use nedb driver.

**Comment by scottwrobinson** [comment] 2016-03-03 19:08
Thanks for posting this. Although, it's actually a duplicate of #25 (which still refers to the old `loadOneAndUpdate()`). Hoping to get to it within the week.

**Closed by scottwrobinson** 2016-03-03 19:08 UTC
Labels: duplicate
