### ISSUE TITLE
How to overwrite hooks after the class is created?

### ISSUE THREAD

**Issue by michaeljota** [scottwrobinson/camo#34] opened 2016-01-16 18:18 UTC
I'm trying to mimic the [Angular-Fullstack](https://github.com/angular-fullstack/generator-angular-fullstack/tree/legacy-2.x.x) sync function over socket.io.

They do it by calling the 'post save' hook in mongoose. However, I'm not able to reproduce this with camo.

I'm aware of Camo having hooks, but they are exposed as Object based. I wonder if there is somehow to get this Class based.

I not sure if I'm making clear myself, I think I'm not.

Sorry for my bad english, and my bad explanation. 

Thanks. 

--

PS: I think maybe this can explain what I mean:
[thing.socket.js](https://github.com/DaftMonk/fullstack-demo/blob/master/server/api/thing/thing.socket.js)

**Comment by scottwrobinson** [comment] 2016-01-18 12:42
Hmm I'm not sure I understand what you want exactly. Can you post the Camo code that you would like to use (even if it doesn't work)? I would have described the hook system as the other way around (class-based as opposed to object-based) since hooks are defined within the `class` declaration and not on a per-instance basis.

**Comment by scottwrobinson** [comment] 2016-01-18 21:02
Okay, I skimmed over your question too fast earlier, I think I know what you're looking for. If you want, you can define any hook within your `Document` class (`preSave`, `postDelete`, etc). But you can _also_ reassign that hook for any `Document` _instance_.

For example, here I give the `scott` instance its own custom `preSave` hook:

```javascript
'use strict';

var connect = require('camo').connect;
var Document = require('camo').Document;

class Person extends Document {
    constructor () {
        super();

        this.name = String;
    }

    preSave() {
        console.log('Original pre save');
    }
}

connect('nedb://memory').then(db => {
    const bill = Person.create({
        name: 'Bill'
    });

    const scott = Person.create({
        name: 'Scott'
    });

    scott.preSave = function() {
        console.log('NEW pre save');
    };

    Promise.all(bill.save(), scott.save()).then(data => {
        console.log('Saved people');
    });

}).catch(err => {
    console.log('Error:', err);
});
```

Here is the result:

```
$ node index.js
Original pre save
NEW pre save
$
```

Is this what you're trying to do? Hope this helps!

**Comment by michaeljota** [comment] 2016-01-18 21:21
No. It would be more like:
```javascript
var names = [];
connect('nedb://memory').then(db => {
    const bill = Person.create({
        name: 'Bill'
    });

    const scott = Person.create({
        name: 'Scott'
    });

    Person.preSave = function() {
        names.push(this.name);
        console.log('NEW pre save');
    };

    Promise.all(bill.save(), scott.save()).then(data => {
        console.log('Saved people');
    });

}).catch(err => {
    console.log('Error:', err);
});
console.log(JSON.stringify(names));
```

Resulting: 

```shell
$ node index.js
NEW pre save
NEW pre save
[{"name":"Bill"},{"name":"Scott"}]
$
```

Can this be done?

I don't know how to reproduce the code in Camo, however, I posted how Mongoose would be.

**Comment by michaeljota** [comment] 2016-01-19 00:19
I just will try this as I did it to see if this works. I think I test it and it did not work.

**Comment by michaeljota** [comment] 2016-01-19 00:25
Ok. I remember why that did not work, at least, I didn't know how to use it

```javascript

'use strict';

var Thing = require('./thing.model');

exports.register = function(socket) {
  Thing.postSave = function (doc){
    onSave(socket, doc);
  });
  Thing.postDelete = function (doc) {
    onRemove(socket, doc);
  });
}

function onSave(socket, doc, cb) {
  socket.emit('thing:save', doc);
}

function onRemove(socket, doc, cb) {
  socket.emit('thing:remove', doc);
}
```

What I want it's the postSave and postDelete hooks to receive the document after saved.

Does it do that?

**Comment by scottwrobinson** [comment] 2016-01-19 00:26
Ah I see. Yes, you are correct, this will not work. The problem is that all of the hooks are instance methods and not static methods. So `Person.preSave` does not exist, but `scott.preSave` does exist, because it is an instance.

**Comment by scottwrobinson** [comment] 2016-01-19 00:35
Can you not just put `names.push(this.name)` in the original class declaration? Or do you need the hook to change often?

This works:

```javascript
'use strict';

var connect = require('camo').connect;
var Document = require('camo').Document;

var names = [];

class Person extends Document {
    constructor () {
        super();

        this.name = String;
    }

    preSave() {
        names.push(this.name);
    }
}

connect('nedb://memory').then(db => {
    const bill = Person.create({
        name: 'Bill'
    });

    const scott = Person.create({
        name: 'Scott'
    });

    Promise.all([bill.save(), scott.save()]).then(data => {
        console.log('Saved people');
        console.log('Names:', JSON.stringify(names));
    }).catch(err => {
        console.log('Err:', err);
    });

}).catch(err => {
    console.log('Error:', err);
});
```

Another way would be to change the `preSave` hook on a per-instance basis, similar to what I showed earlier:

```javascript
var names = [];

var preSaveHook = function() {
    names.push(this.name);
};

connect('nedb://memory').then(db => {
    const bill = Person.create({
        name: 'Bill'
    });

    const scott = Person.create({
        name: 'Scott'
    });

    bill.preSave = preSaveHook;
    scott.preSave = preSaveHook;

    Promise.all(bill.save(), scott.save()).then(data => {
        console.log('Saved people');
    });

}).catch(err => {
    console.log('Error:', err);
});
```

**Comment by michaeljota** [comment] 2016-01-19 01:10
That was just to follow your example.

The one thing that I want it's to send the document over socket. As the last post example. 

But, I'll try to do it that way to see if that works. :+1:

**Comment by michaeljota** [comment] 2016-01-19 02:27
Ok. What I want/need it's the postSave to receive the document saved, to be able to send the document over socket. I think that might be possible.

I'll write some code and let you know.

**Comment by michaeljota** [comment] 2016-01-19 03:46
Wao! Thanks you!

What I did, if anyone ends here:

´´´javascript (The 'SocketManager')

'use strict';

var _socket = null;

function register (socket) {
    _socket = socket;
    console.log('Socket is now: '+_socket);
}

function postSave (collection, doc) {
    console.log(collection+' sended: ' + doc.toJSON());
    if(_socket) {
        _socket.emit(collection+':saved', doc);
    }
}

function postDelete (collection, doc) {
    if(_socket) {
        _socket.emit(collection+':deleted', doc);
    }
}

function postError (err) {
    if(_socket) {
        _socket.emit('error', err);
    }
}

module.exports.register = register;
module.exports.postSave = postSave;
module.exports.postDelete = postDelete;
module.exports.postError = postError;
´´´
Inside the class declaration, overriding the "postSave()" hook.
´´´javascript
    postSave () {
        _postSave ('shapes', this);
    }
´´´
_postSave it's a require from the other file.

Thanks!

**Closed** 2016-01-19 03:48 UTC
Labels: question

**Comment by scottwrobinson** [comment] 2016-01-19 19:26
:thumbsup:

Glad this worked out for you! Let me know if you have any other questions.
